### ISSUE TITLE
Stopping the node on Jenkins doesn't really work

### ISSUE THREAD

**Issue by thescouser89** [thescouser89/ovirt-slaves-plugin#1]

**Comment by thescouser89** [comment]
Lots of thread work involved!

**Comment by tollgen** [comment]
Hi, just checking on this issue, is there a time frame for this functionality as it would be great for my setup.

I am finding that disconnecting a slave in jenkins does not shutdown the vm on ovirt which is how the libvirt plugin works.

**Comment by thescouser89** [comment]
Hi!

By disconnect, do you mean the slave gets marked as 'shutdown on idle'? I think this is an easy thing to implement. Let me know! :)

BTW, hopefully we'll get RHEV 4.0 deployed in our environment sometime next year so I can start working on a 4.0 version with the latest RHEV API.

**Comment by tollgen** [comment]
I find the VM doesn't get shutdown on idle on the ovirt side only gets offline on the Jenkins side.  So in the libvirt plugin it will shutdown the VM on the KVM host either when idle or if you disconnect which would be great if your ovirt plugin did this.  Is this what you found or thinking with this issue?

**Comment by thescouser89** [comment]
Nah it's another issue. But I know what you're talking about! Will dig into the libvirt plugin to see how they do it, then will implement

**Comment by tollgen** [comment]
Excellent, that would be great

**Comment by thescouser89** [comment]
@tollgen Could you try from the latest commit and let me know if that works for you?

Commit: aaf9164b3c755ee98ec7411859e702e5a025ec98

**Comment by tollgen** [comment]
does master support 4.0?  I have the latest ovirt
Getting the below when I try and launch a jenkins slave

Connecting to ovirt server...
java.lang.NullPointerException
ERROR: Launching agent process aborted.
java.lang.NullPointerException
	at org.jenkinsci.plugins.ovirt.OVirtVMLauncher.isVMDown(OVirtVMLauncher.java:122)
	at org.jenkinsci.plugins.ovirt.OVirtVMLauncher.putVMUp(OVirtVMLauncher.java:243)
	at org.jenkinsci.plugins.ovirt.OVirtVMLauncher.launch(OVirtVMLauncher.java:343)
Caused: java.lang.InterruptedException
	at org.jenkinsci.plugins.ovirt.OVirtVMLauncher.handleLaunchFailure(OVirtVMLauncher.java:375)
	at org.jenkinsci.plugins.ovirt.OVirtVMLauncher.launch(OVirtVMLauncher.java:347)
	at hudson.slaves.SlaveComputer$1.call(SlaveComputer.java:285)
	at jenkins.util.ContextResettingExecutorService$2.call(ContextResettingExecutorService.java:46)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by thescouser89** [comment]
@tollgen I'm not supporting 4.0 at this time. Only 3.4 :( I don't have access to a 4.0 instance to test, and I couldn't figure out how to install 4.0 on my laptop. Sorry about that!

**Comment by tollgen** [comment]
Good and bad news.
I was able to test your change and get it working in ovirt 4.0
But I had to add your changes to LucidHorizons fork (https://github.com/LucidHorizons/ovirt-slaves-plugin) to work with my 4.1 instance.  Looks like I will be using this fork going forward, sorry :(

**Comment by thescouser89** [comment]
@tollgen no worries! :) Glad to hear you got it to work on 4.x! :)

**Comment by thescouser89** [comment]
Hopefully once we get an ovirt 4.x deployment at work we can contribute together to get the plugin (whether mine or your fork) in a good shape

**Comment by tollgen** [comment]
Could maybe merge some changes from the fork?

**Comment by thescouser89** [comment]
I would say yes! The master branch will be for ovirt 4.0 and the ovirt 3.x branch for over 3.x. And I guess when ovirt 5 comes out we'll create a branch for ovirt 4. WDYT?

My only issue is I won't be able to test the ovirt 4.0 changes :/ Oh well

**Comment by tollgen** [comment]
I can test builds if needed, I also posted another issue on the fork - if you have any thoughts on that?

https://github.com/LucidHorizons/ovirt-slaves-plugin/issues/14

**Comment by thescouser89** [comment]
I'll check what's up with it

**Comment by joaquin386** [comment]
@tollgen then https://github.com/LucidHorizons/ovirt-slaves-plugin is compatible with ovirt engine 4.1?

**Comment by tollgen** [comment]
Yes it is @joaquin386 
Though I am getting the issue (14) I linked above

**Comment by joaquin386** [comment]
And is the snapshot working for you? I create the snapshot on ovirt 4.1 but it doesn't appear when configuring the slave nodes.

**Comment by tollgen** [comment]
Not sure I haven't tried a snapshot, we don't need snapshots for our builds, maybe log an issue?
